#!/usr/bin/env python

import logging
import sys
import mfgames_tools
import mfgames_font.unicode


reload(sys);
sys.setdefaultencoding('utf-8')


def do_font_tool(arguments):
    mfgames_tools.run_tool(
        ".",
        arguments,
        {
            'unicode-chart':
                mfgames_font.unicode.GenerateUnicodeChart(),
        })


if __name__ == "__main__":
    do_font_tool(sys.argv[1:])
